"use strict";
exports.__esModule = true;
exports.AND = 'AND';
exports.OR = 'OR';
exports.XOR = 'XOR';
exports.NAND = 'NAND';
exports.NOR = 'NOR';
exports.NXOR = 'NXOR';
exports.EXACTLY_ONE = 'EXACTLY_ONE';
exports.TERMINAL = 'TERMINAL';
